---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: http://gitea-http.gitea.svc.k3s-01.47fc5c.com:3000/fraccs/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://operator.min.io
      chart: operator
      targetRevision: 7.1.1
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/minio-operator/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
