---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: romm
  namespace: romm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romm
  template:
    metadata:
      labels:
        app: romm
    spec:
      containers:
        - name: romm
          image: docker.io/rommapp/romm:4.5.0@sha256:79d2ab75ce6bdb8f0c7b1d8bb33a456566de5470d5d0e451fbc0919cc84679e8
          startupProbe:
            httpGet:
              path: /api/heartbeat
              port: 8090
            failureThreshold: 5
            periodSeconds: 20
          volumeMounts:
            - name: romm-data
              mountPath: /romm/assets
              subPath: assets/
            - name: romm-data
              mountPath: /romm/config
              subPath: config/
            - name: romm-data
              mountPath: /romm/resources
              subPath: resources/
            - name: romm-roms
              mountPath: /romm/library/roms
          envFrom:
            - configMapRef:
                name: romm
            - secretRef:
                name: romm
      volumes:
        - name: romm-data
          persistentVolumeClaim:
            claimName: romm-data
        - name: romm-roms
          persistentVolumeClaim:
            claimName: romm-roms
