---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
        access-postgres: "true"
    spec:
      containers:
        - name: prowlarr
          image: docker.io/linuxserver/prowlarr:2.3.0@sha256:67a8aaedcfd6989f3030b937a6a07007310b1dfc7ee8df16d2cbfa48d1c1158c
          volumeMounts:
            - name: prowlarr
              mountPath: /config
          envFrom:
            - configMapRef:
                name: prowlarr
      volumes:
        - name: prowlarr
          persistentVolumeClaim:
            claimName: prowlarr
