---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefly
  namespace: firefly
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`firefly.l.47fc5c.com`)
      kind: Rule
      services:
        - name: firefly
          kind: Service
          port: 8080
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
