---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: gotify
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: docker.io/gotify/server:2.9.0@sha256:4df8c1bb23646b8d8b308e881866474bfae4a9a5b3980e5047f87eb84017e8a0
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 5
            periodSeconds: 20
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gotify-data
              mountPath: /app/data
          envFrom:
            - configMapRef:
                name: gotify
            - secretRef:
                name: gotify
      volumes:
        - name: gotify-data
          persistentVolumeClaim:
            claimName: gotify-data
