---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.2.2@sha256:6f57cf359f57f05c89238680b39ca7cd0e135477e11247ad4beb02cc740bbfda
          volumeMounts:
            - name: immich-server-data
              mountPath: /usr/src/app/upload
            - name: immich-gallery
              mountPath: /usr/src/app/upload/library
          envFrom:
            - configMapRef:
                name: immich-server
            - secretRef:
                name: immich-server
      volumes:
        - name: immich-server-data
          persistentVolumeClaim:
            claimName: immich-server-data
        - name: immich-gallery
          persistentVolumeClaim:
            claimName: immich-gallery
