---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie
  namespace: mealie
spec:
  secretName: mealie-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - mealie.47fc5c.com
