---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie
  namespace: mealie
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCl4B0N+ixk0DYEUoWKXeF37ZcMDpMJOC0BIkuSBMIyFs1DKZmPIry7ZnYM8mRs9CvvLZytW2tpgDQBMCRfTTWxaS89foMxoCUyuU6ELfQvAIbUFH1bePNQNCiKsR7dkAYspqPpFVJkXmKt1EZ4vcFNZ3K0oBvcVGog15oryjLkMCcsdOmOVJ/cd6+xNI4RmXNdpX9noRT+N6q2u24qXDOrKYnb/dAPGotrjGe7hdFRwLTkwPHUooFpQ1NDmHXesgn3vHUx/CN6RA4AZrGicSYeqf8KhfabPqkVShYnwflR21Whri84xRLtHdvDzr93zw/q0BS2oNHMbyIf6t1EG1bJozJpjo6YR4t6xaDYrqm/xQptpCOkcGuCxOF0JcySq98WTMINZeVn8fa0S+GmDZzoVu7q95TlNd5vv3GQ35XcCb3GdtgiwzPttWxrDNT+CWupq7lO/YKCFJjW53YCOoypKa4l5sDnxU+dv4nUFLQaVKHLObzt+LQ0R/uBtek/oOKL2Be8DEJzSWFFH+tJ5rxTKyQvqigHRPC6wNJejbXF0eME6lUF1zu7FKhz0f9iMVGbug8e6HpvERE4ZzWE/JCNhj3cUVzU9hou/od2r8XxV6Z/x8FOKRC0oGisRqN51gQg9uGUAEW14ZwfmlViQvEc36GVbZ5yr11PTf4mearYT6Y08wFQJBM7Ei+6LeYDTeFTgzQwpeERE6A/0V02bIA6aQg06krKVBM=
    POSTGRES_USER: AgCd9wLJzfomPkYZIUhqSqPqz9fZUqL4qOF9SM+P3uvAy8Wzl4PeNFIMykHobExhDXPhjsoNU9fB61zxZuP/DduQW6sAtBd0ETib/XsnifGOjGgqfqIBYYkWGXZshmVOJCTEQkmcQB+yAgDBwXTtEmIOT1sBNpxkUi/qMXlAxxX7Fgs+eSShGxRdY1cLELDOVpMn9GT+EEflt1rfzDpHGTMG+4+VgFGQT6WpUw7hvKfFlD9d1PVrKuDNDDS2LISstyPl0LYjlfaC1diC0RBWKZZod5rMJ4yoptPgpHtdBYIHRfFtQ7kR//TzmhtvQR0r2uNPDAO/BUeOuHmjxDb5zXmRtPL67f5+y2/6+tGYEJpqZfsf/jMkJHfMuwsdnfE5ph9V8B3uGb5+/RuoSrFeawGy/femzQtvDyFV3LFyVA/jbpZoADoLhd6miKJFSfkSZTD5PvDBqOKmGQH5UP3CvyM8w9oc4reFPiYg+zJpyxN/6vxL24lq2Ql8JS5XwPA24tnYNZ65L3BT6x49Sr/awMF+1Ei52mQ8bCGxpZlidOcDbRb6N/+lc5f/+ka59O1Ga3iKywyZokXNmC75FCRfsNq8VndVn0jdDsYW5sPw7yHJO5eGITvYIIqx9z0OI/w708y0MtnjDhSfWdMbqW4dGSkgZXxp4Ntj6+DT1IDP7x2iIyHVjgqvNlYZORXXFfgZRWE2SetegRI=
  template:
    metadata:
      name: mealie
      namespace: mealie
