---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: http://gitea-http.gitea.svc.k3s-01.47fc5c.com:3000/fraccs/infrastructure.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/eck-operator
    - repoURL: http://gitea-http.gitea.svc.k3s-01.47fc5c.com:3000/fraccs/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://helm.elastic.co
      chart: eck-operator
      targetRevision: 3.3.0
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/eck-operator/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
