---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: http://gitea-http.gitea.svc.k3s-01.47fc5c.com:3000/fraccs/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/k3s-01/workloads/mariadb
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
