---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding
  namespace: linkding
data:
  LD_CONTAINER_NAME: "linkding"
  LD_HOST_PORT: "9090"
  LD_HOST_DATA_DIR: "./data"
  LD_DISABLE_BACKGROUND_TASKS: "False"
  LD_DISABLE_URL_VALIDATION: "False"
  LD_ENABLE_AUTH_PROXY: "False"
  LD_DB_ENGINE: "postgres"
  LD_DB_DATABASE: "linkding"
  LD_DB_USER: "linkding"
  LD_DB_HOST: "postgres.postgres.svc.cluster.local"
