---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: renovate
        spec:
          restartPolicy: Never
          containers:
            - name: renovate-bot
              image: docker.io/renovate/renovate:41.171.1@sha256:9c18ae1d4a98ac33a8e076e78117ea4d655f4937f071c401ac2a67109161d8d7
              envFrom:
                - configMapRef:
                    name: renovate-env
                - secretRef:
                    name: renovate
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
