---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: http://gitea-http.gitea.svc.k3s-01.47fc5c.com:3000/fraccs/infrastructure.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/authentik
    - repoURL: http://gitea-http.gitea.svc.k3s-01.47fc5c.com:3000/fraccs/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2025.12.4
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/authentik/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
