---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: docker.io/syncthing/syncthing:2.0.14@sha256:6d2ab058383b533e045cf2c32fc4c6bbe87c612c92bc2aca9f552fb099b2e123
          volumeMounts:
            - name: syncthing-config
              mountPath: /var/syncthing
            - name: syncthing-repos
              mountPath: /repos
          envFrom:
            - configMapRef:
                name: syncthing
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: syncthing-repos
          persistentVolumeClaim:
            claimName: syncthing-repos
