---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: docker.io/pihole/pihole:2025.02.4@sha256:d83cd1ca243eace24c9d2f7320634eb47dee06dcdacb15247fdc1e30efd69438
          startupProbe:
            httpGet:
              path: /admin/api.php?status
              port: 80
            failureThreshold: 5
            periodSeconds: 20
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 80
            - containerPort: 53
          volumeMounts:
            - name: pihole
              mountPath: /etc/pihole
              subPath: etc-pihole/
            - name: pihole
              mountPath: /etc/dnsmasq.d
              subPath: etc-dnsmasq.d/
          envFrom:
            - configMapRef:
                name: pihole
            - secretRef:
                name: pihole
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: pihole
