---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: docker.io/jellyfin/jellyfin:10.11.5@sha256:6d819e9ab067efcf712993b23455cc100ee5585919bb297ea5a109ac00cb626e
          startupProbe:
            httpGet:
              path: /health
              port: 8096
            periodSeconds: 12
            failureThreshold: 5
          volumeMounts:
            - name: jellyfin-data
              mountPath: /cache
              subPath: cache/
            - name: jellyfin-data
              mountPath: /config
              subPath: config/
            - name: jellyfin-movies
              mountPath: /movies
            - name: jellyfin-shows
              mountPath: /shows
      volumes:
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data
        - name: jellyfin-movies
          persistentVolumeClaim:
            claimName: jellyfin-movies
            readOnly: true
        - name: jellyfin-shows
          persistentVolumeClaim:
            claimName: jellyfin-shows
            readOnly: true
