---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: docker.io/jellyfin/jellyfin:10.11.6@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
          startupProbe:
            httpGet:
              path: /health
              port: 8096
            periodSeconds: 12
            failureThreshold: 5
          volumeMounts:
            - name: jellyfin-data
              mountPath: /cache
              subPath: cache/
            - name: jellyfin-data
              mountPath: /config
              subPath: config/
            - name: jellyfin-movies
              mountPath: /movies
            - name: jellyfin-shows
              mountPath: /shows
      volumes:
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data
        - name: jellyfin-movies
          persistentVolumeClaim:
            claimName: jellyfin-movies
            readOnly: true
        - name: jellyfin-shows
          persistentVolumeClaim:
            claimName: jellyfin-shows
            readOnly: true
