---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tubearchivist
  namespace: tubearchivist
spec:
  secretName: tubearchivist-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - tubearchivist.47fc5c.com
