---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: archivebox
  namespace: archivebox
spec:
  secretName: archivebox-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-clusterissuer-acme-letsencrypt-cloudflare
  dnsNames:
    - archivebox.47fc5c.com
