---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: archivebox
  namespace: archivebox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`archivebox.47fc5c.com`)
      kind: Rule
      middlewares:
        - namespace: archivebox
          name: archivebox-ipallowlist
      services:
        - name: archivebox
          kind: Service
          port: 8000
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: archivebox-certificate
