---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://gitea.47fc5c.com/fraccs/infrastructure.git
      targetRevision: HEAD
      path: kubernetes/k3s-01/workloads/elastic-operator
    - repoURL: https://gitea.47fc5c.com/fraccs/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://helm.elastic.co
      chart: elastic-operator
      targetRevision: 3.3.0
      helm:
        valueFiles:
          - $values/kubernetes/k3s-01/workloads/elastic-operator/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
