---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://gitea.47fc5c.com/fraccs/homelab.git
    targetRevision: HEAD
    path: kubernetes/k3s-prod-a/workloads/kavita
  destination:
    server: https://kubernetes.default.svc
    namespace: kavita
