---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kavita
  namespace: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
        - name: kavita
          image: docker.io/jvmilazz0/kavita:0.8.9@sha256:69e9117b9b681849a6f6d5dc8411bfa6a326ed77f78cc49d9cbce49584ff6c0d
          volumeMounts:
            - name: kavita-books
              mountPath: /books
            - name: kavita-data
              mountPath: /kavita/config
          envFrom:
            - configMapRef:
                name: kavita
      volumes:
        - name: kavita-books
          persistentVolumeClaim:
            claimName: kavita-books
        - name: kavita-data
          persistentVolumeClaim:
            claimName: kavita-data
