---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        access-postgres: "true"
    spec:
      containers:
        - name: sonarr
          image: docker.io/linuxserver/sonarr:4.0.16@sha256:8b9f2138ec50fc9e521960868f79d2ad0d529bc610aef19031ea8ff80b54c5e0
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-downloads
              mountPath: /downloads
            - name: sonarr-shows
              mountPath: /shows
          envFrom:
            - configMapRef:
                name: sonarr
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-downloads
          persistentVolumeClaim:
            claimName: sonarr-downloads
        - name: sonarr-shows
          persistentVolumeClaim:
            claimName: sonarr-shows
