---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
        - name: cdio
          image: docker.io/linuxserver/changedetection.io:0.52.6@sha256:a2af77933ae1bacac7c6f0ed760a3680a99ea555c03d9c77dc39dd94e29b80a7
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: cdio
              mountPath: /config
          envFrom:
            - configMapRef:
                name: cdio
      volumes:
        - name: cdio
          persistentVolumeClaim:
            claimName: cdio
