---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
        - name: cdio
          image: docker.io/linuxserver/changedetection.io:0.53.5@sha256:13723ed33a6b06b63172c91e03612fe44e45f916dac468050973aeb426a829cc
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: cdio
              mountPath: /config
          envFrom:
            - configMapRef:
                name: cdio
      volumes:
        - name: cdio
          persistentVolumeClaim:
            claimName: cdio
